---
- name: diodonfrost.java
- name: diodonfrost.vagrant
- name: diodonfrost.packer
- name: diodonfrost.terraform
- name: diodonfrost.terragrunt
- name: diodonfrost.ohmyzsh
- name: diodonfrost.jetbrains_toolbox
